import hashlib,json,os,subprocess,sys,tempfile,time,unittest
from pathlib import Path
S=Path(__file__).parents[1]/'scripts'/'verified_push.py'
P='schema_version=1\nauto_push_default=true\ndoctor_on_start=true\nallow_force_push=false\nrequire_reviewer_ship=true\nrequire_passed_checks=true\nrequire_secret_scan=true\nrequire_attribution=true\nrequire_existing_upstream=true\nrequire_fresh_veto_evidence=true\n'
class T(unittest.TestCase):
 def setUp(self):
  self.t=tempfile.TemporaryDirectory();self.d=Path(self.t.name);self.r=self.d/'r';self.g=self.d/'g';self.x=self.d/'e';self.p=self.d/'p';self.p.write_text(P);self.env=os.environ.copy()
  self.c('git','init','--bare',self.r);self.c('git','init',self.g);self.c('git','-C',self.g,'config','user.email','a@b');self.c('git','-C',self.g,'config','user.name','a');(self.g/'a').write_bytes(b'0\0');self.c('git','-C',self.g,'add','a');self.c('git','-C',self.g,'commit','-m','b');self.c('git','-C',self.g,'branch','-M','main');self.c('git','-C',self.g,'remote','add','origin',self.r);self.c('git','-C',self.g,'push','-u','origin','main');(self.g/'a').write_bytes(b'1\0\xff');self.c('git','-C',self.g,'add','a');self.c('git','-C',self.g,'commit','-m','c');os.chmod(self.p,0o600);self.ev()
 def tearDown(self):self.t.cleanup()
 def c(self,*a,ok=True):
  p=subprocess.run(a,capture_output=True,text=True)
  if ok and p.returncode:self.fail(p.stderr)
  return p
 def ev(self,**z):
  h=self.c('git','-C',self.g,'rev-parse','HEAD').stdout.strip();b=self.c('git','-C',self.g,'rev-parse','@{u}').stdout.strip();q=subprocess.run(['git','-C',self.g,'diff','--binary',f'{b}..{h}'],capture_output=True,check=True).stdout;d=hashlib.sha256(q).hexdigest();z64='0'*64;pd=hashlib.sha256(json.dumps(['a'],sort_keys=True,separators=(',',':')).encode()).hexdigest();x={'schema_version':1,'candidate_oid':h,'patch_digest':d,'checks':[{'name':'u','status':'passed','digest':z64}],'secret_scan':{'status':'passed','candidate_oid':h,'patch_digest':d,'paths_sha256':pd,'digest':z64},'attribution':{'candidate_oid':h,'patch_digest':d,'paths':['a'],'paths_sha256':pd,'digest':z64},'qa':{'verdict':'pass','candidate_oid':h,'patch_digest':d,'digest':z64},'reviewer':{'verdict':'ship','candidate_oid':h,'patch_digest':d,'digest':z64,'independent':True},'fresh_veto':{'status':'clear','digest':z64,'candidate_oid':h,'patch_digest':d,'checked_at':int(time.time())}};x.update(z);self.x.write_text(json.dumps(x))
 def h(self,*a):return subprocess.run([sys.executable,S,*map(str,a)],capture_output=True,text=True,env=self.env)
 def check(self):
  p=self.h('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.assertEqual(p.returncode,0,p.stderr);return json.loads(p.stdout)
 def expire_auth(self,d,stale_evidence=False):
  old=Path(d['authorization']);a=json.loads(old.read_text());now=int(time.time());a['created_at']=now-1000;a['expires_at']=now-100
  if stale_evidence:
   e=json.loads(self.x.read_text());e['fresh_veto']['checked_at']=now-1000;self.x.write_text(json.dumps(e));a['evidence_sha256']=hashlib.sha256(self.x.read_bytes()).hexdigest()
  b=json.dumps(a,sort_keys=True,separators=(',',':')).encode();h=hashlib.sha256(b).hexdigest();new=old.parent/(a['candidate_oid']+'-'+str(a['attempt'])+'-'+h+'.json');old.unlink();new.write_bytes(b);os.chmod(new,0o600);return {'authorization':str(new),'sha256':h,'attempt':a['attempt']},a
 def refused(self,*args):self.assertNotEqual(self.h(*args).returncode,0)
 def test_positive_binary_execute_idempotent(self):
  d=self.check();a=d['authorization'];p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',a,'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0,p.stderr);self.assertEqual(self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',a,'--authorization-sha256',d['sha256']).returncode,0);self.assertEqual(os.stat(a).st_mode&0o777,0o600);state=self.g/'.git/agent';self.assertEqual(os.stat(state).st_mode&0o777,0o700);self.assertTrue(all((os.stat(state/n).st_mode&0o777)==0o700 for n in ('push-authorizations','push-journal','push-receipts')));self.assertEqual(os.stat(state/'push-journal'/(d['sha256']+'.json')).st_mode&0o777,0o600);self.assertEqual(os.stat(state/'push-receipts'/(d['sha256']+'.json')).st_mode&0o777,0o600)
 def test_negative_evidence_policy_sensitive(self):
  for k,v in [('reviewer',{}),('qa',{}),('fresh_veto',{}),('checks',[]),('secret_scan',{})]:self.ev(**{k:v});self.assertNotEqual(self.h('check','--repo',self.g,'--policy',self.p,'--evidence',self.x).returncode,0)
  self.ev();(self.g/'.env').write_text('x');self.c('git','-C',self.g,'add','.env');self.c('git','-C',self.g,'commit','-m','s');self.ev(attribution={'paths':['.env'],'digest':'x'});self.assertNotEqual(self.h('check','--repo',self.g,'--policy',self.p,'--evidence',self.x).returncode,0);self.p.write_text(P+'x=true\n');self.assertNotEqual(self.h('check','--repo',self.g,'--policy',self.p,'--evidence',self.x).returncode,0)
 def test_no_upstream_refused(self):
  self.c('git','-C',self.g,'branch','--unset-upstream');self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_option_like_tracking_remote_refused_before_endpoint_or_state(self):
  self.c('git','-C',self.g,'config','branch.main.remote','--','-option');log=self.install_git_proxy(False);p=self.h('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.assertNotEqual(p.returncode,0);lines=log.read_text().splitlines();self.assertFalse(any(' remote get-url ' in ' '+x+' ' or ' push ' in ' '+x+' ' for x in lines));self.assertFalse(list((self.g/'.git/agent/push-authorizations').glob('*.json')))
 def test_dirty_tracked_refused(self):
  (self.g/'a').write_bytes(b'dirty');self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_dirty_untracked_refused(self):
  (self.g/'new').write_text('x');self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_attribution_mismatch_refused(self):
  self.ev(attribution={});self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_sensitive_env_key_and_private_state_paths_refused(self):
  for name in ('.env.local','client.key','access_token.txt'):
   (self.g/name).write_text('x');self.c('git','-C',self.g,'add',name);self.c('git','-C',self.g,'commit','-m',name);self.ev();self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.c('git','-C',self.g,'reset','--hard','@{u}')
  (self.g/'a').write_bytes(b'2');self.c('git','-C',self.g,'add','a');self.c('git','-C',self.g,'commit','-m','again');self.ev()
 def test_workstation_missing_malformed_unknown_false_and_symlink_refused(self):
  self.p.unlink();self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.p.write_text('bad=[');os.chmod(self.p,0o600);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.p.write_text(P+'unknown=true\n');self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.p.write_text(P.replace('auto_push_default=true','auto_push_default=false'));self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.p.unlink();self.p.symlink_to(self.x);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_project_policy_false_malformed_unknown_force_and_symlink_refused(self):
  q=self.g/'.git/agent/policy.toml';q.parent.mkdir();q.write_text(P.replace('require_secret_scan=true','require_secret_scan=false'));os.chmod(q,0o600);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);q.write_text('x=[');self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);q.write_text(P+'x=true\n');self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);q.write_text(P.replace('allow_force_push=false','allow_force_push=true'));self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);q.unlink();q.symlink_to(self.x);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_evidence_extra_bad_digest_empty_checks_secret_qa_reviewer_veto_refused(self):
  cases=[{'checks':[]},{'checks':[{'name':'x','status':'passed','digest':'bad'}]},{'secret_scan':{}},{'qa':{}},{'reviewer':{}},{'fresh_veto':{}},{'fresh_veto':{'status':'clear','candidate_oid':'x','patch_digest':'x','checked_at':int(time.time())+1,'digest':'0'*64}}]
  for z in cases:self.ev(**z);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
  self.ev(fresh_veto={'status':'clear','candidate_oid':'x','patch_digest':'x','checked_at':int(time.time())-901,'digest':'0'*64});self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
  self.ev();d=json.loads(self.x.read_text());d['extra']=1;self.x.write_text(json.dumps(d));self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_authorization_sha_bytes_extra_path_escape_symlink_expired_refused(self):
  d=self.check();a=Path(d['authorization']);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',a,'--authorization-sha256','0'*64);outside=self.d/'outside';outside.write_bytes(a.read_bytes());os.chmod(outside,0o600);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',outside,'--authorization-sha256',hashlib.sha256(outside.read_bytes()).hexdigest());link=a.parent/'link.json';link.symlink_to(a);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',link,'--authorization-sha256',d['sha256']);obj=json.loads(a.read_text());obj['extra']=1;a.write_text(json.dumps(obj));os.chmod(a,0o600);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',a,'--authorization-sha256',hashlib.sha256(a.read_bytes()).hexdigest());obj.pop('extra');obj['expires_at']=0;a.write_text(json.dumps(obj));os.chmod(a,0o600);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',a,'--authorization-sha256',hashlib.sha256(a.read_bytes()).hexdigest())
 def test_remote_url_drift_refused(self):
  d=self.check();self.c('git','-C',self.g,'remote','set-url','--push','origin',str(self.d/'other'));self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256'])
 def configure_distinct_push_endpoint(self):
  push=self.d/'push';self.c('git','init','--bare',push);self.c('git','-C',self.g,'push',push,'@{u}:refs/heads/main');self.c('git','-C',self.g,'remote','set-url','--push','origin',push);return push
 def test_distinct_fetch_and_push_urls_reconcile_push_endpoint(self):
  push=self.configure_distinct_push_endpoint();base=self.c('git','-C',self.g,'rev-parse','@{u}').stdout.strip();head=self.c('git','-C',self.g,'rev-parse','HEAD').stdout.strip();d=self.check();p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0,p.stderr);self.assertEqual(self.c('git','--git-dir',push,'rev-parse','refs/heads/main').stdout.strip(),head);self.assertEqual(self.c('git','--git-dir',self.r,'rev-parse','refs/heads/main').stdout.strip(),base);state=self.g/'.git/agent/push-receipts';self.assertTrue((state/(d['sha256']+'.json')).is_file());self.assertFalse((state/(d['sha256']+'.absent.json')).exists());self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.assertNotIn(str(push),p.stdout+p.stderr);self.assertNotIn(str(self.r),p.stdout+p.stderr)
 def test_push_endpoint_base_drift_refused_even_when_fetch_tracking_stays_base(self):
  push=self.configure_distinct_push_endpoint();base=self.c('git','-C',self.g,'rev-parse','@{u}').stdout.strip();self.c('git','-C',self.g,'push',push,'HEAD:refs/heads/main');self.assertEqual(self.c('git','-C',self.g,'rev-parse','@{u}').stdout.strip(),base);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_multiple_push_urls_refused_before_authorization_or_push(self):
  other=self.d/'other';self.c('git','init','--bare',other);self.c('git','-C',self.g,'config','--add','remote.origin.pushurl',self.r);self.c('git','-C',self.g,'config','--add','remote.origin.pushurl',other);log=self.install_git_proxy(False);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.assertFalse((self.g/'.git/agent').exists());self.assertFalse(any(' push ' in ' '+x+' ' for x in log.read_text().splitlines()))
 def test_leading_dash_push_endpoint_refused_before_state_or_transport(self):
  state=self.g/'.git/agent';state.mkdir();os.chmod(state,0o755);self.c('git','-C',self.g,'config','remote.origin.pushurl','--','-malicious');self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.assertEqual(state.stat().st_mode&0o777,0o755);self.assertEqual(list(state.iterdir()),[])
 def test_credential_bearing_https_endpoint_refused_without_disclosure(self):
  secret='https://user:password@example.invalid/repo.git';self.c('git','-C',self.g,'config','remote.origin.pushurl',secret);p=self.h('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.assertNotEqual(p.returncode,0);self.assertNotIn(secret,p.stdout+p.stderr);self.assertNotIn('password',p.stdout+p.stderr)
 def test_malformed_bracketed_http_endpoint_refused_without_traceback_or_state(self):
  endpoint='https://[broken.example/repo.git';self.c('git','-C',self.g,'config','remote.origin.pushurl',endpoint);log=self.install_git_proxy(False);p=self.h('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.assertNotEqual(p.returncode,0);self.assertNotIn(endpoint,p.stdout+p.stderr);self.assertNotIn('Traceback',p.stdout+p.stderr);self.assertFalse(any(' push ' in ' '+x+' ' for x in log.read_text().splitlines()));self.assertFalse(list((self.g/'.git/agent/push-authorizations').glob('*.json')));self.assertFalse(list((self.g/'.git/agent/push-journal').glob('*.json')))
 def test_live_remote_base_advance_refused(self):
  clone=self.d/'c';self.c('git','clone',self.r,clone);self.c('git','-C',clone,'config','user.email','a@b');self.c('git','-C',clone,'config','user.name','a');(clone/'z').write_text('z');self.c('git','-C',clone,'add','z');self.c('git','-C',clone,'commit','-m','z');self.c('git','-C',clone,'push');self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_unused_attempt_one_refuses_second_authorization(self):
  self.assertEqual(self.check()['attempt'],1);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_attempt_two_requires_strict_started_and_absent_chain(self):
  d=self.check();self.journal(d);q=self.g/'.git/agent/push-receipts'/(d['sha256']+'.absent.json');q.write_text('{}');os.chmod(q,0o600);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);q.unlink();q.symlink_to(self.x);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def test_recovery_revalidates_policy_evidence_and_local_context(self):
  d=self.check();self.journal(d);self.p.write_text(P.replace('auto_push_default=true','auto_push_default=false'));self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.p.write_text(P);os.chmod(self.p,0o600);self.ev(reviewer={});self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.ev();(self.g/'a').write_text('drift');self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256'])
 def test_idempotent_receipt_revalidates_remote_identity(self):
  d=self.check();self.assertEqual(self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']).returncode,0);self.c('git','-C',self.g,'remote','set-url','--push','origin',str(self.d/'other'));self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256'])
 def test_tracking_remote_name_with_slash_supported_without_split(self):
  self.c('git','-C',self.g,'remote','rename','origin','team/origin');d=self.check();self.assertEqual(self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']).returncode,0)
 def test_expired_unused_authorization_refuses_transport(self):
  d,_=self.expire_auth(self.check());log=self.install_git_proxy(False);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertFalse(any(' push ' in ' '+x+' ' for x in log.read_text().splitlines()))
 def test_expired_authorization_exact_success_receipt_is_idempotent_without_push(self):
  d=self.check();self.assertEqual(self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']).returncode,0);d,a=self.expire_auth(d,True);r={'schema_version':1,'state':'success','candidate_oid':a['candidate_oid'],'ref':a['ref'],'remote_url_sha256':a['remote_url_sha256'],'authorization_sha256':d['sha256'],'attempt':a['attempt'],'completed_at':int(time.time())};rp=self.g/'.git/agent/push-receipts'/(d['sha256']+'.json');rp.write_text(json.dumps(r,sort_keys=True,separators=(',',':')));os.chmod(rp,0o600);log=self.install_git_proxy(False);p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0,p.stderr);self.assertTrue(json.loads(p.stdout)['idempotent']);self.assertFalse(any(' push ' in ' '+x+' ' for x in log.read_text().splitlines()))
 def test_expired_authorization_started_journal_reconciles_candidate_without_push(self):
  d=self.check();self.c('git','-C',self.g,'push','origin','HEAD:refs/heads/main');d,a=self.expire_auth(d,True);self.journal(d);log=self.install_git_proxy(False);p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0,p.stderr);self.assertFalse(any(' push ' in ' '+x+' ' for x in log.read_text().splitlines()))
 def test_extra_force_arguments_rejected(self):
  for flag in ('--force','--force-with-lease'):self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x,flag)
 def test_malformed_or_symlink_receipt_refused(self):
  d=self.check();a=d['authorization'];p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',a,'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0);rp=self.g/'.git/agent/push-receipts'/(d['sha256']+'.json');rp.write_text('{}');os.chmod(rp,0o600);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',a,'--authorization-sha256',d['sha256']);rp.unlink();target=self.d/'receipt';target.write_text('{}');rp.symlink_to(target);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',a,'--authorization-sha256',d['sha256'])
 def journal(self,d):
  q=self.g/'.git/agent/push-journal'/(d['sha256']+'.json');q.write_text(json.dumps({'schema_version':1,'state':'started','authorization_sha256':d['sha256'],'attempt':d['attempt']},sort_keys=True,separators=(',',':')));os.chmod(q,0o600)
 def test_started_crash_reconciliation_remote_candidate(self):
  d=self.check();self.c('git','-C',self.g,'push','origin','HEAD:refs/heads/main');self.journal(d);p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0,p.stderr)
 def test_started_crash_reconciliation_remote_base_then_attempt_two(self):
  d=self.check();self.journal(d);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);d2=self.check();self.assertEqual(d2['attempt'],2);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x);self.assertEqual(self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d2['authorization'],'--authorization-sha256',d2['sha256']).returncode,0)
 def test_started_crash_divergent_remote_creates_terminal_unknown(self):
  d=self.check();clone=self.d/'d';self.c('git','clone',self.r,clone);self.c('git','-C',clone,'config','user.email','a@b');self.c('git','-C',clone,'config','user.name','a');(clone/'z').write_text('z');self.c('git','-C',clone,'add','z');self.c('git','-C',clone,'commit','-m','z');self.c('git','-C',clone,'push');self.journal(d);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.refused('check','--repo',self.g,'--policy',self.p,'--evidence',self.x)
 def install_git_proxy(self,nonzero=False):
  real=subprocess.run(['command','-v','git'],shell=True,capture_output=True,text=True).stdout.strip() or '/usr/bin/git';bindir=self.d/'bin';bindir.mkdir();log=self.d/'argv.json';proxy=bindir/'git';proxy.write_text('#!/bin/sh\nprintf "%s\\n" "$*" >> "'+str(log)+'"\n"'+real+'" "$@"\nrc=$?\ncase " $* " in *" push "*) exit '+('1' if nonzero else '$rc')+';; esac\nexit $rc\n');proxy.chmod(0o755);self.env['PATH']=str(bindir)+os.pathsep+self.env['PATH'];return log
 def install_pushurl_race_proxy(self,new_endpoint):
  real=subprocess.run(['command','-v','git'],shell=True,capture_output=True,text=True).stdout.strip() or '/usr/bin/git';bindir=self.d/'race-bin';bindir.mkdir();log=self.d/'race-argv';proxy=bindir/'git';proxy.write_text('#!/bin/sh\nprintf "%s\\n" "$*" >> "'+str(log)+'"\ncase " $* " in *" push "*) "'+real+'" -C "'+str(self.g)+'" remote set-url --push origin "'+str(new_endpoint)+'";; esac\n"'+real+'" "$@"\n');proxy.chmod(0o755);self.env['PATH']=str(bindir)+os.pathsep+self.env['PATH'];return log
 def test_pushurl_race_uses_captured_endpoint_and_same_process_reconciliation(self):
  a=self.d/'endpoint-A';b=self.d/'endpoint-B';self.c('git','init','--bare',a);self.c('git','init','--bare',b);self.c('git','-C',self.g,'push',a,'@{u}:refs/heads/main');self.c('git','-C',self.g,'push',b,'@{u}:refs/heads/main');self.c('git','-C',self.g,'remote','set-url','--push','origin',a);d=self.check();base=self.c('git','-C',self.g,'rev-parse','@{u}').stdout.strip();head=self.c('git','-C',self.g,'rev-parse','HEAD').stdout.strip();log=self.install_pushurl_race_proxy(b);p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0,p.stderr);self.assertEqual(self.c('git','--git-dir',a,'rev-parse','refs/heads/main').stdout.strip(),head);self.assertEqual(self.c('git','--git-dir',b,'rev-parse','refs/heads/main').stdout.strip(),base);push=[x for x in log.read_text().splitlines() if ' push ' in ' '+x+' '];self.assertEqual(len(push),1);self.assertIn(' push -- '+str(a)+' ',push[0]);self.assertNotIn(' origin ',push[0]);self.assertTrue((self.g/'.git/agent/push-receipts'/(d['sha256']+'.json')).is_file());state=b''.join(x.read_bytes() for x in (self.g/'.git/agent').rglob('*') if x.is_file());self.assertNotIn(str(a).encode(),state);self.assertNotIn(str(b).encode(),state);self.assertNotIn(str(a),p.stdout+p.stderr);self.assertNotIn(str(b),p.stdout+p.stderr)
 def test_restarted_started_recovery_pushurl_drift_is_unknown_without_querying_new_endpoint(self):
  a=self.d/'recovery-A';b=self.d/'recovery-B';self.c('git','init','--bare',a);self.c('git','init','--bare',b);self.c('git','-C',self.g,'push',a,'@{u}:refs/heads/main');self.c('git','-C',self.g,'push',b,'@{u}:refs/heads/main');self.c('git','-C',self.g,'remote','set-url','--push','origin',a);d=self.check();self.journal(d);base=self.c('git','--git-dir',b,'rev-parse','refs/heads/main').stdout.strip();self.c('git','-C',self.g,'remote','set-url','--push','origin',b);log=self.install_git_proxy(False);self.refused('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertEqual(self.c('git','--git-dir',b,'rev-parse','refs/heads/main').stdout.strip(),base);self.assertFalse(any('ls-remote --refs '+str(b) in x for x in log.read_text().splitlines()));self.assertTrue(list((self.g/'.git/agent/push-receipts').glob('*.unknown.json')))
 def test_push_nonzero_but_remote_candidate_writes_success_receipt(self):
  log=self.install_git_proxy(True);d=self.check();p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0,p.stderr);self.assertTrue((self.g/'.git/agent/push-receipts'/(d['sha256']+'.json')).is_file())
 def test_recorded_push_argv_exact_non_force_refspec(self):
  log=self.install_git_proxy(False);d=self.check();p=self.h('execute','--repo',self.g,'--policy',self.p,'--evidence',self.x,'--authorization',d['authorization'],'--authorization-sha256',d['sha256']);self.assertEqual(p.returncode,0,p.stderr);lines=log.read_text().splitlines();push=[x for x in lines if ' push ' in ' '+x+' '];self.assertEqual(len(push),1);self.assertNotIn('--force',push[0]);self.assertNotIn('--force-with-lease',push[0]);self.assertIn(' push -- '+str(self.r)+' ',push[0]);self.assertNotIn(' origin ',push[0]);self.assertTrue(push[0].endswith(self.c('git','-C',self.g,'rev-parse','HEAD').stdout.strip()+':refs/heads/main'))
if __name__=='__main__':unittest.main()
